version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: nest-tv-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: jx159357
      MYSQL_DATABASE: nest_tv
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - nest-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: nest-tv-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nest-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 30s

  # NestJS 后端
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-tv-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: nest_user
      DB_PASSWORD: nest_password
      DB_DATABASE: nest_tv
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: nest-tv-production-docker-super-secret-key
    ports:
      - "3334:3000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
      timeout: 10s
      retries: 5
      interval: 30s

  # Vue3 前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nest-tv-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - nest-network
    environment:
      - VITE_API_URL=http://localhost:3334
      - VITE_WS_URL=ws://localhost:3334

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: nest-tv-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    networks:
      - nest-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  nest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16